config/routes.rb
Rails.application.routes.draw do
  resources :tax_and_discounts
  resources :line_items
  resources :products
  resources :categories
  devise_for :users

  namespace :invoices do
    resources :line_items, only: [:create, :destroy]
    resources :tax_and_discount_polies, only: [:create, :destroy]
    resource :calculations, only: [:create]
  end

  resources :invoices do
    collection do
      post 'calculate_sub_total'
    end
  end
  # devise_for :admin_users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
  #  Defines the root path route ("/")
  # root "posts#index"
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  has_many :tax_and_discount_polies, as: :tax_discountable, dependent: :destroy

  DRAFT = 'draft'
  PENDING = 'pending'
  PAID = 'paid'
  enum status: { draft: DRAFT, pending: PENDING, paid: PAID }

  validates :status, presence: true, inclusion: { in: statuses.keys }
  validates :name, presence: true
  validates :line_items, presence: true

  has_many :line_items, dependent: :destroy
  accepts_nested_attributes_for :line_items

  has_many :tax_and_discounts
  accepts_nested_attributes_for :tax_and_discount_polies

  before_save :calculate_sub_total

  private

  def calculate_sub_total
    self.total, self.sub_total = InvoiceAmountCalculator.new(line_items, tax_and_discount_polies).call
  end
end

app/controllers/invoices/amount_calculations_controller.rb
# this Invoices module class action is used at six scenarios
# 1. when user adds/removes a line item and tax and discount fields
# 2. when user updates the quantity of line item
# 3. when user updates the unit rate of line item
# 4. when user updates the amount of tax and discount
# 5. when user updates the tax type of tax and discount
# 6. when user updates the td type of tax and discount

module Invoices
  class AmountCalculationsController < ApplicationController
    def calculate_sub_total
      line_items = params[:lineItemsAttributes].map do |line_item|
        if line_item[:quantity].present? && line_item[:unitRate].present?
          LineItem.new(
            quantity: line_item[:quantity].to_f,
            unit_rate: line_item[:unitRate].to_f
          )
        end
      end

      tax_and_discount_polys = params[:taxAndDiscountPolyAttributes].map do |td_poly|
        TaxAndDiscountPoly.new(
          amount: td_poly[:amount].to_f,
          td_type: td_poly[:td_type],
          name: td_poly[:name],
          tax_type: td_poly[:tax_type]
        )
      end
      
      @sub_total = ::InvoiceAmountCalculator.new.calculate_sub_total(line_items, tax_and_discount_polys)
    end
  end
end

app/controllers/invoices/calculations_controller.rb
# this Invoices module class action is used at six scenarios
# 1. when user adds/removes a line item and tax and discount fields
# 2. when user updates the quantity of line item
# 3. when user updates the unit rate of line item
# 4. when user updates the amount of tax and discount
# 5. when user updates the tax type of tax and discount
# 6. when user updates the td type of tax and discount
module Invoices
  class CalculationsController < ApplicationController # rubocop:disable Style/Documentation
    def create # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
      invoice = Invoice.new
      @line_item_details = {}
      line_items = calculation_params[:lineItemsAttributes].map do |line_item|
        tax_and_discount_polies_attributes = TaxAndDiscount.where(id: line_item[:tdIds]).map do |td|
          { td_type: td.td_type, amount: td.amount, name: td.name }
        end
        next unless line_item[:quantity].present? && line_item[:unitRate].present?

        li = LineItem.new(
          quantity: line_item[:quantity].to_f,
          unit_rate: line_item[:unitRate].to_f,
          unit: line_item[:unit],
          tax_and_discount_polies_attributes: tax_and_discount_polies_attributes
        )
        # The objId attribute is used to uniquely identify each line item in the calculation_params.
        @line_item_details[line_item[:objId]] = { total: li.total, tax_and_discount_polies_attributes: tax_and_discount_polies_attributes }

        li
      end

      invoice.line_items = line_items
      if calculation_params[:taxAndDiscountPolyAttributes].present?
        tax_and_discount_polys = calculation_params[:taxAndDiscountPolyAttributes].map do |td_poly|
          TaxAndDiscountPoly.new(amount: td_poly[:amount].to_f, td_type: td_poly[:td_type], name: td_poly[:name] )
        end
      end

      invoice.tax_and_discount_polies = tax_and_discount_polys || []
      @total, @sub_total, @tax_or_discount = InvoiceAmountCalculator.new(invoice.line_items, invoice.tax_and_discount_polies).call
    end

    private

    def calculation_params
      params.require(:calculation).permit(
        :taxAndDiscountPolyAttributes,
        lineItemsAttributes: [:quantity, :unitRate, :unit, :objId, { tdIds: [] }],
        taxAndDiscountPolyAttributes: %i[amount td_type name]
      )
    end
  end
end

app/controllers/invoices/line_items_controller.rb
module Invoices
  class LineItemsController < ApplicationController
    def create
      @product = Product.find_by(id: params[:productId])
      if @product
        @line_item = LineItem.new(
          item_name: @product.name,
          quantity: 1,
          unit_rate: @product.unit_rate,
          product_id: @product.id,
        )
      else
        item_name, quantity, unit_rate = params[:productId].split(';')
        @line_item = LineItem.new(
          item_name: item_name,
          quantity: quantity || 1,
          unit_rate: unit_rate || 0.0,
          product_id: nil
        )
      end
    end

    def destroy
      @line_item = LineItem.find_by(id: params[:id])
      @line_item.destroy if @line_item.present? && @line_item.persisted?
    end
  end
end

app/controllers/invoices/tax_and_discount_polies_controller.rb
module Invoices
  class TaxAndDiscountPoliesController < ApplicationController
    def create
      @tax_and_discount = TaxAndDiscount.find_by(id: params[:taxAndDiscountId])
      if @tax_and_discount
        @tax_and_discount_poly = TaxAndDiscountPoly.new(
          name: @tax_and_discount.name,
          amount: @tax_and_discount.amount,
          td_type: @tax_and_discount.td_type,
          tax_and_discount_id: @tax_and_discount.id
        )
      else
        name, amount, td_type, tax_type = params[:taxAndDiscountId].split(';')
        @tax_and_discount_poly = TaxAndDiscountPoly.new(
          name: name,
          amount: amount || 0.0,
          td_type: td_type == 'discount' ? 'discount' : 'tax' ,
          tax_and_discount_id: nil,
        )
      end
    end

    def destroy
      @tax_and_discount_poly = TaxAndDiscountPoly.find_by(id: params[:taxAndDiscountId])
      @tax_and_discount_poly.destroy if @tax_and_discount_poly.present? && @tax_and_discount_poly.persisted?
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[new edit]
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show; end

  # GET /invoices/new
  def new
    @invoice = Invoice.new(user: current_user, status: Invoice::DRAFT)
  end

  # GET /invoices/1/edit
  def edit; end

  # POST /invoices or /invoices.json
  def create
    @invoice = InvoiceObjectBuilderForCreate.new(invoice_params).call
    @invoice.user = current_user
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoice_url(@invoice), notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        set_category
        format.turbo_stream
      end
    end
  rescue ActiveRecord::RecordInvalid => e
    @exception = e.message

    respond_to(&:turbo_stream)
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    @invoice = InvoiceObjectBuilderForUpdate.new(params[:id], invoice_params).call
    @invoice.user = current_user
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoice_url(@invoice), notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        set_category
        format.turbo_stream { render turbo_stream: turbo_stream.replace('invoice_errors', partial: 'invoices/errors', locals: { errors: @invoice.errors }) }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy!
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def set_category
    @categories = Category.includes(:products).where(user_id: current_user.id)
  end

  # Only allow a list of trusted parameters through.
  def invoice_params
    params.require(:invoice).permit(
      :id, :name, :status, :payment_date, :due_date, :note,
      line_items_attributes: [:id, :item_name, :unit_rate, :quantity, :unit, :product_id, tax_and_discount_ids: []],
      tax_and_discount_polies_attributes: %i[id name td_type amount tax_and_discount_id]
    )
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def categories(invoice)
    selected = invoice.line_items.map { |line_item| line_item.item_name }
    return [] unless @categories
    
    @categories.map do |category|
      [category.name, category.products.map { |product| [product.name, product.id, { selected: selected.include?(product.name) }] }]
    end
  end

  def td_options(current_user, object)
    selected = object.tax_and_discount_polies.map(&:tax_and_discount_id)
    selected_ids = object.tax_and_discount_polies.map { |tdp| { id: tdp.tax_and_discount_id, name: tdp.name, p_id: tdp.id }}

    tds = current_user.tax_and_discounts
    [
      ['Taxes', tds.tax.map { |t| [t.name, t.id, { selected: selected.include?(t.id), data: { poly_id: selected_ids.select {|td| td[:id] == t.id }} }] }],
      ['Discount', tds.discount.map { |d| [d.name, d.id, { selected: selected.include?(d.id), data: { poly_id: selected_ids.select {|td| td[:id] == d.id }} }] }]
    ]
  end
end

app/views/invoices/_errors.html.erb
<% if errors.any? %>
  <div class="alert alert-danger">
    <h2><%= pluralize(errors.count, "error") %> something is missing:</h2>
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
  </div>
<% end %>

app/views/invoices/_form.html.erb
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
  <%= form_with(model: invoice, id: "new_invoice_form", class: 'row g-3') do |form| %>
    <% presenter = FormPresenter.new(invoice, self, 'form-control') %>
    <div class="col-md-3">
      <%= presenter.label(:name, 'form-label') %>
      <%= form.text_field :name, presenter.field_options(:name, 'form-control') %>
      <%= presenter.error_container_for(:name) %>
    </div>

    <div class="col-md-3">
      <%= form.label :status, class: 'form-label' %>
      <%= form.select :status, Invoice.statuses.keys.map{ |w| [w.humanize, w]}, { prompt: 'Select Status' }, {class: 'form-select'} %>
    </div>

    <div class="col-md-3">
      <%= form.label :due_date, class: 'form-label' %>
      <%= form.date_field :due_date, class: 'form-control' %>
    </div>

    <div class="col-md-3">
      <%= form.label :payment_date, class: 'form-label' %>
      <%= form.date_field :payment_date, class: 'form-control' %>
    </div>

    <div class="col-12">
      <div data-controller="invoice" data-invoice-edit-value="<%= action_name == 'edit' %>">
        <%= presenter.label(:line_items, 'form-label') %>
        <%= select_tag :product_id, grouped_options_for_select(categories(form.object)),
          presenter.field_options(:line_items, 'form-select',
          prompt: 'Select Line Item',
          multiple: true,
          data: {invoice_target: 'product'},
          id: 'product_id') %>    
        <%= presenter.error_container_for(:line_items) %>
    
        <div class="row">
          <div class="col-md-3">
            <%= form.label :item_name, class: 'form-label' %>
          </div>  

          <div class="col-md-1">
            <%= form.label :quantity, class: 'form-label' %>
          </div>  

          <div class="col-md-2">
            <%= form.label :unit_rate, class: 'form-label' %>
          </div>

          <div class="col-md-1 d-flex justify-content-center">
            <%= form.label :unit, class: 'form-label' %>
          </div>

          <div class="col-md-2">
            <%= form.label :tax_and_discount, class: 'form-label' %>
          </div>

            <div class="col-md-3 d-flex justify-content-center">
            <%= form.label :total_amount, class: 'form-label' %>
          </div>
        </div>

        <div id="line_item">
        </div>

        <% invoice.line_items.each do |line_item| %>
          <%= render partial: 'line_item_fields', locals: { line_item: line_item } %>
        <% end %>
        
        <%= form.label :tax_and_discount, class: 'pt-4'%>
        <%= select_tag :tax_and_discount, grouped_options_for_select(td_options(current_user, form.object)),
          class: 'form-select',
          prompt: 'Select Tax/Discount',
          multiple: true,
          data: {invoice_target: 'product'},
          id: 'tax_and_discount' %>
      
        <div class="row">
          <div class="col-md-4">
            <%= form.label :name, class: 'form-label' %>
          </div>  

          <div class="col-md-4">
            <%= form.label :amount, class: 'form-label' %>
          </div>  

          <div class="col-md-4">
            <%= form.label :td_type, class: 'form-label' %>
          </div>
        </div>

        <div id="tax_and_discount_poly">
        </div>

        <% invoice.tax_and_discount_polies.each do |tax_and_discount_poly| %>
          <%= render partial: 'td_poly_fields', locals: { tax_and_discount_poly: tax_and_discount_poly } %>
        <% end %>

      </div>
    </div>
    
    <div class="col-12">
      <%= form.label :note, class: "form-label" %>
      <%= form.text_area :note, class: 'form-control' %>
    </div>

    <div>
      <%= form.submit class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/invoices/_invoice.html.erb
<div id="<%= dom_id invoice %>">
  <p>
    <strong>User:</strong>
    <%= invoice.user_id %>
  </p>

  <p>
    <strong>Line items count:</strong>
    <%= invoice.line_items_count %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= invoice.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= invoice.status %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= invoice.total %>
  </p>

  <p>
    <strong>Sub total:</strong>
    <%= invoice.sub_total %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= invoice.note %>
  </p>

  <p>
    <strong>Payment date:</strong>
    <%= invoice.payment_date %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= invoice.due_date %>
  </p>

  <p>
    <strong>Line Item:</strong>
    <ol>
      <% invoice.line_items.each do |line_item| %>
        <li>
          <%= line_item.item_name %> | <%= line_item.quantity %> | <%= line_item.unit_rate %>
        </li>
      <% end %>
    </ol>
  </p>

</div>

app/views/invoices/_line_item_fields.html.erb
<%= fields_for "invoice[line_items_attributes][#{line_item.persisted? ? line_item.id : line_item.hash}]", line_item do |form|%>
  <% presenter = FormPresenter.new(line_item, self, 'form-control') %>
  <% if line_item.persisted? %>
    <div class="row" data-invoice-target="lineitem" id="<%= dom_id(line_item) %>">
  <% else %>
    <div class="row" data-invoice-target="lineitem" id="<%= line_item.hash %>">
  <% end %>
  
    <div class="col-md-3">
      <%= form.text_field :item_name, presenter.field_options(:item_name, 'form-control') %>
      <%= presenter.error_container_for(:item_name) %>
    </div>  

    <div class="col-md-1">
      <%= form.number_field :quantity, presenter.field_options(:quantity, "form-control", data: {action: "change->invoice#handleInputChange" }) %>
      <%= presenter.error_container_for(:quantity) %>
    </div>  

    <div class="col-md-2">
      <%= form.number_field :unit_rate, class: "form-control", data: {action: "change->invoice#handleInputChange" } %>
    </div>

    <div class="col-md-1">
      <%= form.text_field :unit, class: "form-control" %>
    </div>
    
    <div class="col-md-2">
      <%= form.select :tax_and_discount_ids, grouped_options_for_select(td_options(current_user, form.object)),
        { prompt: 'Select Item', include_hidden: false },
        multiple: true,
        autocomplete: 'off'
      %>
    </div>

    <div class="col-md-3 d-flex justify-content-center">
      <span id= <%= "line_item_total_#{line_item.persisted? ? line_item.id : line_item.hash}"%>>
      </span>
    </div>

    <%= form.hidden_field :product_id %>
    <%= form.hidden_field :id %>
    <%= hidden_field_tag :obj_id, line_item.persisted? ? line_item.id : line_item.hash %>
  </div>
<% end %>

<div id="line_item">
</div>

app/views/invoices/_summary_section.html.erb
<div class="card text-dark bg-light mb-3" style="width: 11rem;">
  <div class="card-body">
    <h5 class="card-title">Summary</h5>
    <div id="subtotal">
      <p>Subtotal: <%= number_to_currency(0.0) %></p>
    </div>
    <div id="tax_or_discount">
    </div>
    <div id="total">
      <p>Total: <%= number_to_currency(0.0) %></p>
    </div>
  </div>
</div>

app/views/invoices/_td_poly_fields.html.erb
<%= fields_for "invoice[tax_and_discount_polies_attributes][#{tax_and_discount_poly.persisted? ? tax_and_discount_poly.id : tax_and_discount_poly.hash}]", tax_and_discount_poly do |form|%>
  <% if tax_and_discount_poly.persisted? %>
    <div class="row" data-invoice-target="taxAndDiscountPoly" id="<%= dom_id(tax_and_discount_poly) %>" data-params=<%= params %>>
  <% else %>
    <div class="row" data-invoice-target="taxAndDiscountPoly" id="<%= tax_and_discount_poly.hash %>" data-params=<%= params %>>
  <% end %>

    <div class="col-md-4">
      <%= form.text_field :name, class: "form-control" %>
    </div>  

    <div class="col-md-4">
      <%= form.number_field :amount, class: "form-control", data: {action: "change->invoice#handleTaxAndDiscountPolyChange" }%>
    </div>  

    <div class="col-md-4">
      <%= form.text_field :td_type, class: "form-control" %>
    </div>

    <%= form.hidden_field :tax_and_discount_id %>
    <%= form.hidden_field :id %>
  </div>
<% end %>

<div id="tax_and_discount_poly">
</div>

app/views/invoices/create.turbo_stream.erb
<%=  @exception if @exception.present? %>
<%= turbo_stream.replace 'new_invoice_form' do %>
  <%= render "form", invoice: @invoice %>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>
<div id="invoice_errors"></div>

<div class="d-flex flex-column flex-xl-row">
  <div class="flex-lg-row-fluid me-lg-5 me-xl-3 mb-3">
    <%= render "form", invoice: @invoice %>
  </div>
  <div class="flex-column flex-lg-row-auto w-150 w-xl-200px mb-10">
    <div class="flex-column flex-lg-row-auto w-150 w-xl-200px mb-10">
      <%= render partial: "summary_section", locals: { subtotal: @subtotal, tax_or_discount: @tax_or_discount, total: @total } %>
    </div>
  </div>
</div>

<br>

<div>
  <%= link_to "Show this invoice", @invoice %> |
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Invoices</h1>

<div id="invoices">
  <% @invoices.each_with_index do |invoice, index| %>
    
    <p>
      <%= link_to "#{index} #{invoice.name} Show", invoice %>
    </p>
  <% end %>
</div>

<%= link_to "New invoice", new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<div class="d-flex flex-column flex-xl-row">
  <div class="flex-lg-row-fluid me-lg-5 me-xl-3 mb-3">
    <%= render "form", invoice: @invoice %>
  </div>
  <div class="flex-column flex-lg-row-auto w-150 w-xl-200px mb-10">
    <%= render partial: "summary_section", locals: { subtotal: @subtotal, tax_or_discount: @tax_or_discount, total: @total } %>
  </div>
</div>

<div>
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @invoice %>

<div>
  <%= link_to "Edit this invoice", edit_invoice_path(@invoice) %> |
  <%= link_to "Back to invoices", invoices_path %><br><br>

  <%= button_to "Destroy this invoice", @invoice, method: :delete %>
</div>