config/routes.rb
Rails.application.routes.draw do
  resources :tax_and_discounts
  resources :line_items
  resources :products
  resources :categories
  devise_for :users

  namespace :invoices do
    resources :line_items, only: [:create, :destroy]
    resources :tax_and_discount_polies, only: [:create, :destroy]
    resource :calculations, only: [:create]
  end

  resources :invoices do
    collection do
      post 'calculate_sub_total'
    end
  end
  # devise_for :admin_users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
  #  Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :name, presence: true
  validates :category_id, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    
    # @product.category_id = product_params[:category_id] --> by doing this we can also handle the category_id
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :unit_rate, :category_id, :unit)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% presenter = FormPresenter.new(product, self, 'form-control') %>
  <div class="row mb-3">
    <div class="col">
      <%= presenter.label(:name, 'form-label') %>
      <%= form.text_field :name, presenter.field_options(:name, 'form-control') %>
      <%= presenter.error_container_for(:name) %>
    </div>

    <div class="col">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="col">
      <%= form.label :unit_rate, class: "form-label" %>
      <%= form.text_field :unit_rate, class: "form-control" %>
    </div>

    <div class="col">
      <%= presenter.label(:category_id, 'form-label') %>
      <%= form.select :category_id, options_for_select(current_user.categories.map { |category| [category.name, category.id ] }), {prompt: "select category"}, presenter.field_options(:category_id, 'form-select') %>
      <%= presenter.error_container_for(:category_id) %>
    </div>

    <div class="col">
      <%= form.label :unit, class: "form-label" %>
      <%= form.text_field :unit, class: "form-control" %>
    </div>
  </div>

  <div class="col">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Unit rate:</strong>
    <%= product.unit_rate %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category_id %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= product.unit %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each_with_index do |product, index| %>
    <p>
      <%= link_to "#{index}  #{product.name} show", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %><br><br>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>