config/routes.rb
Rails.application.routes.draw do
  resources :tax_and_discounts
  resources :line_items
  resources :products
  resources :categories
  devise_for :users

  namespace :invoices do
    resources :line_items, only: [:create, :destroy]
    resources :tax_and_discount_polies, only: [:create, :destroy]
    resource :calculations, only: [:create]
  end

  resources :invoices do
    collection do
      post 'calculate_sub_total'
    end
  end
  # devise_for :admin_users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
  #  Defines the root path route ("/")
  # root "posts#index"
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :invoice
  belongs_to :product, optional: true
  validates :item_name, presence: true
  validates :quantity, presence: true, numericality: { greater_than: 0 }

  has_many :tax_and_discount_polies, as: :tax_discountable
  has_many :tax_and_discounts, through: :tax_and_discount_polies, source: :tax_and_discount
  accepts_nested_attributes_for :tax_and_discount_polies

  def total
    quantity * unit_rate
  end

  def discounts
    tax_and_discount_polies.select(&:discount?)
  end

  def taxes
    tax_and_discount_polies.select(&:tax?)
  end
end

app/controllers/invoices/line_items_controller.rb
module Invoices
  class LineItemsController < ApplicationController
    def create
      @product = Product.find_by(id: params[:productId])
      if @product
        @line_item = LineItem.new(
          item_name: @product.name,
          quantity: 1,
          unit_rate: @product.unit_rate,
          product_id: @product.id,
        )
      else
        item_name, quantity, unit_rate = params[:productId].split(';')
        @line_item = LineItem.new(
          item_name: item_name,
          quantity: quantity || 1,
          unit_rate: unit_rate || 0.0,
          product_id: nil
        )
      end
    end

    def destroy
      @line_item = LineItem.find_by(id: params[:id])
      @line_item.destroy if @line_item.present? && @line_item.persisted?
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully created." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy!

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:item_name, :unit_rate, :quantity, :invoice_id, :product_id, :unit, :vendor_currency, :vendor_amount, :meta)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item_name, style: "display: block" %>
    <%= form.text_field :item_name %>
  </div>

  <div>
    <%= form.label :unit_rate, style: "display: block" %>
    <%= form.text_field :unit_rate %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.number_field :product_id %>
  </div>

  <div>
  <%= form.label :invoice_id, style: "display: block" %>
  <%= form.number_field :invoice_id %>
  </div>

  <div>
    <%= form.label :unit, style: "display: block" %>
    <%= form.text_field :unit %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<div id="<%= dom_id line_item %>">
  <p>
    <strong>Item name:</strong>
    <%= line_item.item_name %>
  </p>

  <p>
    <strong>Unit rate:</strong>
    <%= line_item.unit_rate %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= line_item.quantity %>
  </p>

  <p>
    <strong>Invoice:</strong>
    <%= line_item.invoice_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= line_item.invoice_id %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= line_item.unit %>
  </p>


</div>

app/views/line_items/edit.html.erb
<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show this line item", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New line item", new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @line_item %>

<div>
  <%= link_to "Edit this line item", edit_line_item_path(@line_item) %> |
  <%= link_to "Back to line items", line_items_path %>

  <%= button_to "Destroy this line item", @line_item, method: :delete %>
</div>